import { Injectable } from '@angular/core';
import { Device } from './device.model';

export interface ParseResult {
  nodeId?: string;
  patch?: Partial<Device>;
}

// Meshtastic serial log format:
// LEVEL  | HH:MM:SS UPTIME [Module] message
//
// NOTE: pos@<hex> in GPS lines is a Unix timestamp in hex, NOT the node ID.
// The stable hardware node ID comes from:
//   1. Startup log: "[NodeDB] my node num = 0x<id>"
//   2. NimBLE telemetry packet: "fr=0x<id>" when Portnum=67 (TELEMETRY_APP)

@Injectable({ providedIn: 'root' })
export class MeshtasticParserService {

  parseLine(line: string): ParseResult {

    // ── 1. Hardware node ID: startup log ────────────────────────────────────
    // INFO | 0 [NodeDB] my node num = 0x0ACB0984
    // INFO | 0 [NodeDB] myNodeNum = 181534084
    const nodeDb = line.match(
      /\[NodeDB\].*(?:my\s*node\s*num|myNodeNum)\s*[=:]\s*(?:0x)?([0-9a-fA-F]+)/i
    );
    if (nodeDb) {
      const raw = nodeDb[1];
      // Could be decimal or hex; if it looks like hex (has a-f), keep as-is, else convert
      const nodeId = /[a-fA-F]/.test(raw)
        ? raw.toLowerCase()
        : parseInt(raw, 10).toString(16).padStart(8, '0');
      return { nodeId, patch: { status: 'online' } };
    }

    // Startup banner: "nodeNum: 0x0ACB0984" or "nodeNum=0x0ACB0984"
    const startupNum = line.match(/nodeNum\s*[=:]\s*(?:0x)?([0-9a-fA-F]+)/i);
    if (startupNum) {
      const raw = startupNum[1];
      const nodeId = /[a-fA-F]/.test(raw)
        ? raw.toLowerCase()
        : parseInt(raw, 10).toString(16).padStart(8, '0');
      return { nodeId, patch: { status: 'online' } };
    }

    // ── 2. Hardware node ID: NimBLE local telemetry packet ──────────────────
    // [NimbleBluetooth] phone downloaded packet (... fr=0x0acb0984 ... Portnum=67 ...)
    // Portnum=67 = TELEMETRY_APP → generated by THIS device → fr= is local node ID
    const nimbleTel = line.match(
      /\[NimbleBluetooth\].*fr=0x([0-9a-f]+).*Portnum=67/i
    );
    if (nimbleTel) {
      return { nodeId: nimbleTel[1].toLowerCase(), patch: { status: 'online' } };
    }

    // ── 3. GPS: full fix with coordinates ───────────────────────────────────
    // [GPS] New GPS pos@<timestamp_hex> lat=<lat> lon=<lon> alt=<alt> pdop=<x> speed=<x> sats=<n>
    // pos@ value is a Unix timestamp, NOT the node ID — extract only the coordinates
    const gps = line.match(
      /\[GPS\] New GPS pos@[^ ]+\s+lat=([\d.+-]+)\s+lon=([\d.+-]+)\s+alt=([\d-]+).*?pdop=([\d.]+).*?speed=([\d.]+).*?sats=(\d+)/
    );
    if (gps) {
      return {
        patch: {
          lat:   parseFloat(gps[1]),
          lng:   parseFloat(gps[2]),
          alt:   parseFloat(gps[3]),
          pdop:  parseFloat(gps[4]),
          speed: parseFloat(gps[5]),
          sats:  parseInt(gps[6], 10),
          hasGps: true,
          status: 'online',
        },
      };
    }

    // [GPS] updatePosition LOCAL pos@<timestamp_hex> ... lat=<int*1e-7> lon=<int*1e-7> alt=<m>
    // "LOCAL" confirms this is the local device's position; pos@ value is a timestamp
    const updLocal = line.match(
      /\[GPS\] updatePosition LOCAL pos@[^ ]+.*lat=(-?\d+)\s+lon=(-?\d+)\s+alt=(-?\d+)/
    );
    if (updLocal) {
      return {
        patch: {
          lat: parseInt(updLocal[1], 10) * 1e-7,
          lng: parseInt(updLocal[2], 10) * 1e-7,
          alt: parseInt(updLocal[3], 10),
          hasGps: true,
          status: 'online',
        },
      };
    }

    // ── 4. Device telemetry ──────────────────────────────────────────────────
    // [DeviceTelemetry] Send: air_util_tx=X, channel_utilization=X, battery_level=X, voltage=X, uptime=X
    const tel = line.match(
      /\[DeviceTelemetry\] Send:.*air_util_tx=([\d.]+).*channel_utilization=([\d.]+).*battery_level=(\d+).*voltage=([\d.]+).*uptime=(\d+)/
    );
    if (tel) {
      return {
        patch: {
          airUtilTx:          parseFloat(tel[1]),
          channelUtilization: parseFloat(tel[2]),
          battery:            Math.min(100, parseInt(tel[3], 10)),
          voltage:            parseFloat(tel[4]),
          uptime:             parseInt(tel[5], 10),
          status:             'online',
        },
      };
    }

    // ── 5. Power / charging ──────────────────────────────────────────────────
    // [Power] Battery: usbPower=1, isCharging=1, batMv=4360, batPct=100
    const pwr = line.match(
      /\[Power\] Battery: usbPower=(\d+), isCharging=(\d+), batMv=(\d+), batPct=(\d+)/
    );
    if (pwr) {
      return {
        patch: {
          usbPower:   pwr[1] === '1',
          isCharging: pwr[2] === '1',
          batMv:      parseInt(pwr[3], 10),
          battery:    Math.min(100, parseInt(pwr[4], 10)),
          status:     'online',
        },
      };
    }

    return {};
  }
}
